@echo off

echo This is an installation/update script
echo generated by nebulder (https://github.com/erykjj/nebulder)
echo for automating the deployment of a Nebula network
echo MIT License (c) 2023 Eryk J
echo.

set scriptpath=%~dp0
echo Script directory: %scriptpath%
set /p targetpath= Target directory: 
if NOT "%targetpath:~-1%"=="\" set targetpath=%targetpath%\
echo.

if NOT exist %scriptpath%\nebula.exe (
    if NOT exist %targetpath%\nebula.exe (
        echo ERROR: nebula.exe binary NOT FOUND!
        echo Ensure you download the latest for your platform
        echo from https://github.com/slackhq/nebula/releases/latest
        set /p k= Press ENTER to terminate
        goto :eof
    ) else (
        set binary=%targetpath%nebula.exe
    )
) else (
    set binary=%scriptpath%nebula.exe
)

if NOT exist %scriptpath%\dist\windows\wintun\bin\ (
    if NOT exist %targetpath%\dist\windows\wintun\bin\ (
        echo ERROR: wintun.dll driver NOT FOUND!
        echo Ensure you download the latest for your platform
        echo from https://github.com/slackhq/nebula/releases/latest
        set /p k= Press ENTER to terminate
        goto :eof
    )
)

echo Stopping nebula service
%scriptpath%/nebula.exe -service stop
timeout /t 3 /nobreak > NUL
%scriptpath%/nebula.exe -service uninstall
timeout /t 2 /nobreak > NUL
echo.

echo Updating config.yaml with correct paths
echo Target directory: %targetpath%
setlocal enableextensions disabledelayedexpansion
set find=/etc/nebula/nebula10/
set file=%scriptpath%\config.yaml
for /f "delims=" %%i in ('type "%file%" ^& break ^> "%file%" ') do (
    set "line=%%i"
    setlocal enabledelayedexpansion
    >>"%file%" echo(!line:%find%=%targetpath%!
    endlocal
)
echo.

echo Copying new files to %targetpath%
xcopy %scriptpath%\* %targetpath% /E /V /I /Y /Q
echo.

echo Starting nebula service
%targetpath%\nebula.exe -service install -config %targetpath%\config.yaml
timeout /t 3 /nobreak > NUL
%targetpath%\nebula.exe -service start
echo.

echo Done. You can remove this deployment package
set /p k= Press ENTER to close
