@echo off

echo This is an installation/update script
echo generated by nebulder (https://github.com/erykjj/nebulder)
echo for automating the deployment of a Nebula network
echo MIT License (c) 2023 Eryk J
echo.

set scriptpath=%~dp0
echo Script directory: %scriptpath%
set /p d= Target directory: 
if NOT "%d:~-1%"=="\" set d=%d%\
echo.

echo Stopping nebula service
%scriptpath%/nebula.exe -service stop
timeout /t 3 /nobreak > NUL
%scriptpath%/nebula.exe -service uninstall
timeout /t 2 /nobreak > NUL
echo.

echo Updating config.yaml with correct paths
echo Target directory: %d%
setlocal enableextensions disabledelayedexpansion
set find=/etc/nebula/nebula10/
set file=%scriptpath%/config.yaml
for /f "delims=" %%i in ('type "%file%" ^& break ^> "%file%" ') do (
    set "line=%%i"
    setlocal enabledelayedexpansion
    >>"%file%" echo(!line:%find%=%d%!
    endlocal
)
echo.

echo Copying new files to %d%
xcopy %scriptpath%\* %d% /E /V /I /Y /Q
echo.

echo Starting nebula service
%d%\nebula.exe -service install -config %d%\config.yaml
timeout /t 3 /nobreak > NUL
%d%\nebula.exe -service start
echo.

echo Done. You can remove this deployment package
set /p k= Press ENTER to close
