# ============================================================================
# Deployment script for Windows - execute as administrator in PowerShell
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================

$ErrorActionPreference = "Stop"
$TargetPath = "C:\nebula\@@tun_device@@"

function Write-Log { param([string]$Message) Write-Host "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] $Message" }

function Test-Admin {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Uninstall-NebulaService {
    $serviceName = "Nebula"
    $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue

    if ($service -and $service.Status -eq "Running") {
        Write-Log "Stopping Nebula service"
        & "$TargetPath\nebula.exe" -service stop
        Start-Sleep -Seconds 3
    }

    if ($service) {
        & "$TargetPath\nebula.exe" -service uninstall
        Start-Sleep -Seconds 5
    }
}

function Install-NebulaService {
    $serviceName = "Nebula"

    & "$TargetPath\nebula.exe" -service install -config "$TargetPath\config.yaml"
    Start-Sleep -Seconds 3

    if (-not (Get-Service -Name $serviceName -ErrorAction SilentlyContinue)) {
        throw "Service installation failed - service not found"
    }

    Write-Log "Starting service"
    & "$TargetPath\nebula.exe" -service start
    Start-Sleep -Seconds 2
}

function Get-NebulaVersion {
    if (Test-Path "$TargetPath\nebula.exe") {
        try {
            $output = & "$TargetPath\nebula.exe" --version 2>&1
            if ($LASTEXITCODE -eq 0) {
                $match = [regex]::Match($output, 'Version:\s*([0-9\.]+)')
                if ($match.Success) {
                    return $match.Groups[1].Value
                }
            }
        }
        catch {}
    }
    return "unknown"
}

function Create-ScheduledTask {
    $updateBatPath = "$TargetPath\update.bat"
    $updatePs1Path = "$TargetPath\update.ps1"
    $taskName = "Nebula-@@tun_device@@ Auto-Update"

    if (-not (Test-Path $updateBatPath)) {
        Write-Log "update.bat not found"
        return $false
    }

    if (-not (Test-Path $updatePs1Path)) {
        Write-Log "update.ps1 not found"
        return $false
    }

    $action = New-ScheduledTaskAction -Execute $updateBatPath -WorkingDirectory $TargetPath
    $trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 15) -RepetitionDuration (New-TimeSpan -Days 3650)
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries `
                    -DontStopIfGoingOnBatteries `
                    -ExecutionTimeLimit (New-TimeSpan -Minutes 10) `
                    -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)
    
    try {
        $task = Register-ScheduledTask -TaskName $taskName `
                    -Action $action -Trigger $trigger `
                    -Principal $principal -Settings $settings `
                    -Force -ErrorAction Stop
        
        Write-Log "Started scheduled task: $taskName"
        return $true
    }
    catch {
        Write-Log "Failed to create scheduled task: $taskName"
        return $false
    }
}

function Remove-ScheduledTask {
    $taskName = "Nebula-@@tun_device@@ Auto-Update"
    try {
        $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
        if ($task) {
            Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
        }
    }
    catch {}
}

try {
    Write-Log "Nebula Deployment Script"

    if (-not (Test-Admin)) {
        throw "Run as Administrator"
    }

    if (-not (Test-Path $TargetPath)) {
        New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
    }

    $SourceDir = $PSScriptRoot
    $sourceNebula = Test-Path "$SourceDir\nebula.exe"
    $targetNebula = Test-Path "$TargetPath\nebula.exe"

    if (-not $sourceNebula -and -not $targetNebula) {
        throw "nebula.exe not found in source package ($SourceDir) OR target directory ($TargetPath)"
    }

    if ($sourceNebula) {
        Write-Log "Using nebula.exe from deployment package"
    } else {
        Write-Log "Using existing nebula.exe"
    }

    if (-not (Test-Path "$SourceDir\config.yaml")) {
        throw "config.yaml not found in source package"
    }

    Uninstall-NebulaService

    Write-Log "Copying files"

    Get-ChildItem -Path $SourceDir -Recurse | ForEach-Object {
        $relativePath = $_.FullName.Substring($SourceDir.Length + 1)
        $destination = Join-Path $TargetPath $relativePath

        if ($_.PSIsContainer) {
            New-Item -ItemType Directory -Path $destination -Force | Out-Null
        } else {
            Copy-Item -Path $_.FullName -Destination $destination -Force
        }
    }

    if (Test-Path "$TargetPath\node") {
        $node = (Get-Content "$TargetPath\node" -Raw).Trim()
        Write-Log "Node: $node"
    }

    if (Test-Path "$TargetPath\version") {
        $version = (Get-Content "$TargetPath\version" -Raw).Trim()
        Write-Log "Package version: $version"
    }

    $nebulaVersion = Get-NebulaVersion
    Write-Log "Nebula binary version: $nebulaVersion"

    Install-NebulaService

    $updateConfPath = "$TargetPath\update.conf"
    if (Test-Path $updateConfPath) {
        Remove-ScheduledTask
        Create-ScheduledTask | Out-Null
    }

    Write-Log "Deployment completed"
    exit 0
}
catch {
    Write-Host "ERROR: $_" -ForegroundColor Red
    Write-Log "ERROR: $_"
    Write-Log "Deployment failed"
    exit 1
}