#!/bin/bash

# ============================================================================
# Deployment script for Linux - execute with sudo bash
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================


echo -e "\nThis is an installation/update script generated by nebulder (https://github.com/erykjj/nebulder)\nfor automating the deployment of a Nebula network device under Linux with systemd\n"

if [ "$(id -u)" != "0" ]; then
    echo -e "* Because of the high-level access required to execute these commands,\n  this script needs to be run as root\n"
    exit 1
fi

if [[ ! -x "nebula" ]] && [[ ! -x "/usr/lib/nebula/nebula" ]]; then
    echo -e "* ERROR: nebula binary not found!\n"
    echo -e "\n  Download the latest nebula binary from:"
    echo "    https://github.com/slackhq/nebula/releases/latest"
    exit 1
fi

if [[ -d "/etc/nebula/@@tun_device@@" ]]; then
  echo "* Cleaning up previous settings"
  systemctl stop nebula_@@tun_device@@.service 2>/dev/null || true
  rm -rf /etc/nebula/@@tun_device@@
  rm /usr/lib/nebula/@@tun_device@@-update.sh
  echo -e "  Previous key/config files removed\n"
fi

echo -e "* Installing nebula binary and update script to /usr/lib/nebula/"
id nebula >/dev/null 2>&1 || useradd -rM nebula
mkdir -p /usr/lib/nebula
chown root:nebula /usr/lib/nebula
chmod 750 /usr/lib/nebula
mkdir -p /etc/nebula/@@tun_device@@

if [[ -x "nebula" ]]; then
  install -m 750 nebula /usr/lib/nebula/nebula
  chown root:nebula /usr/lib/nebula/nebula
  setcap cap_net_admin=+pe /usr/lib/nebula/nebula 2>/dev/null || true
  nebula_version=$(./nebula --version 2>/dev/null | grep -o "Version: [0-9.]*" | cut -d' ' -f2 || echo "unknown")
  echo "  Binary installed (version: ${nebula_version:-unknown})"
else
  if [[ -x "/usr/lib/nebula/nebula" ]]; then
    nebula_version=$(/usr/lib/nebula/nebula --version 2>/dev/null | grep -o "Version: [0-9.]*" | cut -d' ' -f2 || echo "unknown")
    echo "  Using existing binary (version: ${nebula_version:-unknown})"
  else
    echo -e "  ERROR: No nebula binary found!"
    exit 1
  fi
fi

if [[ -f "update.conf" ]]; then
  install -m 740 update.sh /usr/lib/nebula/@@tun_device@@-update.sh
  chown root:nebula /usr/lib/nebula/@@tun_device@@-update.sh
  cp -t /etc/nebula/@@tun_device@@ update.conf
  chmod 600 /etc/nebula/@@tun_device@@/update.conf
  cp nebula_@@tun_device@@-update.service nebula_@@tun_device@@-update.timer /etc/systemd/system/
  echo -e "  Update script installed\n"
fi

echo "* Putting key/config files in /etc/nebula/@@tun_device@@"
cp -t /etc/nebula/@@tun_device@@ host.* ca.crt config.yaml version node
echo "  Files copied"
chown -R nebula:nebula /etc/nebula/@@tun_device@@
chmod 600 /etc/nebula/@@tun_device@@/host.* /etc/nebula/@@tun_device@@/ca.crt
chmod 644 /etc/nebula/@@tun_device@@/config.yaml /etc/nebula/@@tun_device@@/version /etc/nebula/@@tun_device@@/node
echo -e "  Permissions set\n"

echo "* Setting up systemd unit files in /etc/systemd/system/"
cp nebula_@@tun_device@@.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable nebula_@@tun_device@@.service > /dev/null 2>&1
systemctl start nebula_@@tun_device@@.service

if [[ -f "update.conf" ]]; then
  systemctl enable nebula_@@tun_device@@-update.service > /dev/null 2>&1
  systemctl enable nebula_@@tun_device@@-update.timer > /dev/null 2>&1
  systemctl start nebula_@@tun_device@@-update.timer
fi

echo "  nebula_@@tun_device@@.service: $(systemctl is-active nebula_@@tun_device@@.service 2>/dev/null || echo 'inactive')"
if [[ -f "update.conf" ]]; then
  echo "  nebula_@@tun_device@@-update.timer: $(systemctl is-active nebula_@@tun_device@@-update.timer 2>/dev/null || echo 'inactive')"
  if systemctl is-active --quiet nebula_@@tun_device@@-update.timer 2>/dev/null; then
    echo "  nebula_@@tun_device@@-update.service: enabled"
  else
    echo "  nebula_@@tun_device@@-update.service: disabled"
  fi
  echo ""
fi

echo "* If the device is a lighthouse, you may also need to add a rule to your firewall"
echo "  to allow traffic to the @@tun_device@@ network device port. Example:"
echo "  # sudo ufw allow 4242/udp"
echo -e "  # sudo ufw reload\n"

echo -e "Done. If there were no errors, you can remove this deployment package\n"

exit 0