#!/bin/bash

# MIT License:    Copyright (c) 2023 Eryk J.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


echo -e "\nThis is a clean-up script generated by nebulder (https://github.com/erykjj/nebulder)\nfor automating the removal of a Nebula network device under Linux with systemd\n"

if [ "$(id -u)" != "0" ]; then
 echo -e "* Because of the high-level access required to execute these commands,\n  this script needs to be run a root\n"
 exit 1
fi

echo "* Cleaning up systemd: /etc/systemd/system/nebula_@@tun_device@@.service"
systemctl stop nebula_@@tun_device@@.service
echo "  Service stopped"
systemctl disable nebula_@@tun_device@@.service 
echo "  Service disabled"
rm /etc/systemd/system/nebula_@@tun_device@@.service
systemctl daemon-reload
echo -e "  Unit file removed\n"

echo "* Removing config and keys from /etc/nebula/@@tun_device@@"
rm -rf /etc/nebula/@@tun_device@@
echo -e "  Files removed\n"

echo -e "You may also need to check your firewall rules and remove the nebula binary from /usr/bin\n"

echo -e "Done. If there were no errors, you can remove deployment package\n"

exit 0