#!/bin/bash

# MIT License:    Copyright (c) 2025 Eryk J.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


echo -e "\nThis is a clean-up script generated by nebulder (https://github.com/erykjj/nebulder)\nfor automating the removal of a Nebula network device under Linux with systemd\n"

if [ "$(id -u)" != "0" ]; then
 echo -e "* Because of the high-level access required to execute these commands,\n  this script needs to be run as root\n"
 exit 1
fi

echo "* Cleaning up systemd services"
systemctl stop nebula_@@tun_device@@-update.timer 2>/dev/null || true
systemctl stop nebula_@@tun_device@@-update.service 2>/dev/null || true
systemctl stop nebula_@@tun_device@@.service 2>/dev/null || true
systemctl disable nebula_@@tun_device@@-update.timer 2>/dev/null || true
systemctl disable nebula_@@tun_device@@-update.service 2>/dev/null || true
systemctl disable nebula_@@tun_device@@.service 2>/dev/null || true
rm -f /etc/systemd/system/nebula_@@tun_device@@.service \
      /etc/systemd/system/nebula_@@tun_device@@-update.service \
      /etc/systemd/system/nebula_@@tun_device@@-update.timer 2>/dev/null || true
systemctl daemon-reload 2>/dev/null || true
echo -e "  Unit files removed\n"

echo "* Removing config and keys from /etc/nebula/@@tun_device@@"
if [[ -d "/etc/nebula/@@tun_device@@" ]]; then
  rm -rf /etc/nebula/@@tun_device@@
  echo "  Config directory removed"
fi

echo "* Removing update script"
if [[ -f "/usr/lib/nebula/nebula_@@tun_device@@-update.sh" ]]; then
  rm -f "/usr/lib/nebula/nebula_@@tun_device@@-update.sh"
  echo "  Update script removed"
fi

echo -e "\n* Optional cleanup (may affect other Nebula networks):"
echo "  - Remove binary if unused: sudo rm /usr/lib/nebula/nebula /usr/bin/nebula"
echo "  - Remove nebula directory if empty: sudo rmdir /usr/lib/nebula"
echo "  - Remove nebula user if no other networks: sudo userdel nebula"
echo "  - Check firewall rules: sudo ufw status numbered"

echo -e "\nDone. If there were no errors, you can remove this deployment package\n"

exit 0