#!/bin/bash

# ============================================================================
# Clean-up script for Linux - execute with sudo bash
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================


echo -e "\nThis is a clean-up script generated by nebulder (https://github.com/erykjj/nebulder)\nfor automating the removal of a Nebula network device under Linux with systemd\n"

if [ "$(id -u)" != "0" ]; then
 echo -e "* Because of the high-level access required to execute these commands,\n  this script needs to be run as root\n"
 exit 1
fi

echo "* Cleaning up systemd services"
systemctl stop nebula_@@tun_device@@-update.timer 2>/dev/null || true
systemctl stop nebula_@@tun_device@@-update.service 2>/dev/null || true
systemctl stop nebula_@@tun_device@@.service 2>/dev/null || true
systemctl disable nebula_@@tun_device@@-update.timer 2>/dev/null || true
systemctl disable nebula_@@tun_device@@-update.service 2>/dev/null || true
systemctl disable nebula_@@tun_device@@.service 2>/dev/null || true
rm -f /etc/systemd/system/nebula_@@tun_device@@.service \
      /etc/systemd/system/nebula_@@tun_device@@-update.service \
      /etc/systemd/system/nebula_@@tun_device@@-update.timer 2>/dev/null || true
systemctl daemon-reload 2>/dev/null || true
echo -e "  Unit files removed\n"

echo "* Removing config and keys from /etc/nebula/@@tun_device@@"
if [[ -d "/etc/nebula/@@tun_device@@" ]]; then
  rm -rf /etc/nebula/@@tun_device@@
  echo "  Config directory removed"
fi

echo "* Removing update script"
if [[ -d "/var/run/nebula/@@tun_device@@" ]]; then
  rm -rf "/var/run/nebula/@@tun_device@@"
fi
if [[ -f "/usr/lib/nebula/@@tun_device@@-update.sh" ]]; then
  rm -f "/usr/lib/nebula/@@tun_device@@-update.sh"
  echo "  Update script removed"
fi

echo -e "\n* Optional cleanup (may affect other Nebula networks):"
echo "  - Remove binary if unused: sudo rm /usr/lib/nebula/nebula"
echo "  - Remove nebula directory if empty: sudo rmdir /usr/lib/nebula"
echo "  - Remove nebula user if no other networks: sudo userdel nebula"
echo "  - Check firewall rules: sudo ufw status numbered"

echo -e "\nDone. If there were no errors, you can remove this deployment package\n"

exit 0