# Update server configuration
UPDATE_SERVER="https://my.network.com/nebula"
AUTH_USER="nebula"
AUTH_PASS="authorized"

# Update repo configuration
GITHUB_REPO="owner/repo"
GITHUB_TOKEN="fine_graned_personal_access_token_with_READ&WRITE_permissions_to_contents_on_private_update_repo"
UPDATE_TOKEN="fine_graned_personal_access_token_with_READ-ONLY_permissions_to_contents_on_private_update_repo"

UPDATE_PRIMARY="github" # or "server"
NTFY_CHANNEL="MyNebulaAlerts"
