# Update server configuration
UPDATE_SERVER="https://my.network.com/nebula" # your server URL
AUTH_USER="nebula" # username for authenticating to your server
AUTH_PASS="authorized" # password for authentication

# Update repo configuration
GITHUB_REPO="owner/repo" # your PRIVATE repo for updates
GITHUB_TOKEN="github_pat_..." # READ-WRITE token (Contents) on your private update repo
UPDATE_TOKEN="github_pat_..." # READ-ONLY token (Contents) on your private update repo

UPDATE_PRIMARY="github" # if both sources configured: "github" or "server" (which to try first)
NTFY_CHANNEL="MyNebulaAlerts" # if you wish to receive update notifications via ntfy.sh
