#!/bin/bash

# ============================================================================
# Deployment script for Linux - execute with sudo bash
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================

set -euo pipefail

# Configuration
EXEC_DIR="/usr/lib/nebula/@@tun_device@@"
CONFIG_DIR="/etc/nebula/@@tun_device@@"
SERVICE_DIR="/etc/systemd/system"
SERVICE_NAME="nebula_@@tun_device@@"

echo -e "\nThis is an installation/update script generated by nebulder (https://github.com/erykjj/nebulder)\nfor automating the deployment of a Nebula network device under Linux with systemd\n"

if [ "$(id -u)" != "0" ]; then
    echo -e "* Because of the high-level access required to execute these commands,\n  this script needs to be run as root\n"
    exit 1
fi

if [[ ! -x "nebula" ]] && [[ ! -x "${EXEC_DIR}/nebula" ]]; then
    echo -e "* ERROR: nebula binary not found!\n"
    echo -e "\n  Download the latest nebula binary from:"
    echo "    https://github.com/slackhq/nebula/releases/latest"
    exit 1
fi

if [[ -d "${CONFIG_DIR}" ]]; then
  echo "* Cleaning up previous settings"
  systemctl stop nebula_@@tun_device@@.service 2>/dev/null || true
  rm -rf "${CONFIG_DIR}"
  rm -f "${EXEC_DIR}"/*.sh
  echo -e "  Previous scripts & key/config files removed\n"
fi

echo -e "* Installing nebula binary and scripts to ${EXEC_DIR}"
id nebula >/dev/null 2>&1 || useradd -rM nebula
mkdir -p "${EXEC_DIR}"
install -m 740 *.sh "${EXEC_DIR}"
chown root:nebula "${EXEC_DIR}"/*.sh
chmod 750 "${EXEC_DIR}"
mkdir -p "${CONFIG_DIR}"

if [[ -x "nebula" ]]; then
  install -m 750 nebula "${EXEC_DIR}"
  chown root:nebula "${EXEC_DIR}/nebula"
  setcap cap_net_admin=+pe "${EXEC_DIR}/nebula" 2>/dev/null || true
  nebula_version=$(./nebula --version 2>/dev/null | grep -o "Version: [0-9.]*" | cut -d' ' -f2 || echo "unknown")
  echo "  Binary installed (version: ${nebula_version:-unknown})"
else
  if [[ -x "${EXEC_DIR}/nebula" ]]; then
    nebula_version=$("${EXEC_DIR}/nebula" --version 2>/dev/null | grep -o "Version: [0-9.]*" | cut -d' ' -f2 || echo "unknown")
    echo "  Using existing binary (version: ${nebula_version:-unknown})"
  fi
fi

if [[ -f "update.conf" ]]; then
  cp -t "${CONFIG_DIR}" update.conf
  chmod 600 "${CONFIG_DIR}/update.conf"
  cp "${SERVICE_NAME}-update.service" "${SERVICE_NAME}-update.timer" "${SERVICE_DIR}"
  echo -e "  Update script installed\n"
fi

echo "* Putting key/config files in ${CONFIG_DIR}"
cp -t "${CONFIG_DIR}" host.* ca.crt config.yaml version node
echo "  Files copied"
chown -R nebula:nebula "${CONFIG_DIR}"
chmod 600 "${CONFIG_DIR}/host.*" "${CONFIG_DIR}/ca.crt"
chmod 644 "${CONFIG_DIR}/config.yaml" "${CONFIG_DIR}/version" "${CONFIG_DIR}/node"
echo -e "  Permissions set\n"

echo "* Setting up systemd unit files in ${SERVICE_DIR}"
cp "${SERVICE_NAME}.service" "${SERVICE_DIR}"
systemctl daemon-reload
systemctl enable "${SERVICE_NAME}.service" > /dev/null 2>&1
systemctl start "${SERVICE_NAME}.service"

if [[ -f "update.conf" ]]; then
  systemctl enable "${SERVICE_NAME}-update.service" > /dev/null 2>&1
  systemctl enable "${SERVICE_NAME}-update.timer" > /dev/null 2>&1
  systemctl start "${SERVICE_NAME}-update.timer"
fi

echo "  ${SERVICE_NAME}.service: $(systemctl is-active "${SERVICE_NAME}.service" 2>/dev/null || echo 'inactive')"
if [[ -f "update.conf" ]]; then
  echo "  ${SERVICE_NAME}-update.timer: $(systemctl is-active "${SERVICE_NAME}-update.timer" 2>/dev/null || echo 'inactive')"
  if systemctl is-active --quiet "${SERVICE_NAME}-update.timer" 2>/dev/null; then
    echo "  ${SERVICE_NAME}-update.service: enabled"
  else
    echo "  ${SERVICE_NAME}-update.service: disabled"
  fi
  echo ""
fi

echo "* If the device is a lighthouse, you may also need to add a rule to your firewall"
echo "  to allow traffic to the @@tun_device@@ network device port. Example:"
echo "  # sudo ufw allow 4242/udp"
echo -e "  # sudo ufw reload\n"

echo -e "Done. If there were no errors, you can remove this deployment package\n"

exit 0