#!/bin/bash

# ============================================================================
# Deployment script for Linux - execute with sudo bash
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================

set -euo pipefail

EXEC_DIR="/usr/local/lib/nebula/@@tun_device@@"
NEBULA_BIN_SOURCE=""
NEBULA_BIN_TARGET="${EXEC_DIR}/nebula"
CONFIG_DIR="/usr/local/etc/nebula/@@tun_device@@"
LAUNCH_DAEMONS_DIR="/Library/LaunchDaemons"
SERVICE_NAME="nebula_@@tun_device@@"

echo -e "\nmacOS deployment script for Nebula network @@tun_device@@\n"

if [[ "$(id -u)" != "0" ]]; then
    echo "This script must be run as root (use sudo)."
    exit 1
fi

echo "* Handling Nebula binary"
if [[ -x "./nebula" ]]; then
    NEBULA_BIN_SOURCE="./nebula"
fi
if [[ -n "${NEBULA_BIN_SOURCE}" ]]; then
    mkdir -p "${EXEC_DIR}"
    install -m 755 "${NEBULA_BIN_SOURCE}" "${NEBULA_BIN_TARGET}"
else
    if [[ -x "${NEBULA_BIN_TARGET}" ]]; then
        echo "  Using existing binary at ${NEBULA_BIN_TARGET} (no binary in package)."
    else
        echo "ERROR: Nebula binary not found in package or at ${NEBULA_BIN_TARGET}"
        echo "Download from: https://github.com/slackhq/nebula/releases/latest"
        exit 1
    fi
fi
NEBULA_VERSION=$("${NEBULA_BIN_TARGET}" --version 2>/dev/null | grep -o "Version: [0-9.]*" | cut -d' ' -f2 || echo "unknown")
echo "  Version: ${NEBULA_VERSION:-unknown}"

echo -e "\n* Stopping and unloading services"
sudo launchctl bootout system "${LAUNCH_DAEMONS_DIR}/${SERVICE_NAME}.plist" 2>/dev/null || true

echo -e "\n* Preparing directories"
mkdir -p "${CONFIG_DIR}" "${EXEC_DIR}"

echo -e "\n* Installing configuration and scripts"
cp -f host.* ca.crt config.yaml version node "${CONFIG_DIR}/" 2>/dev/null || {
    echo "ERROR: Required config files missing."
    exit 1
}
install -m 740 deploy.sh remove.sh "${EXEC_DIR}/" 2>/dev/null || true
if [[ -f "./update.conf" ]]; then
    cp -f ./update.conf "${CONFIG_DIR}/"
    chmod 600 "${CONFIG_DIR}/update.conf"
fi

echo -e "\n* Configuring launchd services"
if [[ -f "./nebula_@@tun_device@@.plist" ]]; then
    install -m 644 "./nebula_@@tun_device@@.plist" "${LAUNCH_DAEMONS_DIR}/"
    sudo launchctl bootstrap system "${LAUNCH_DAEMONS_DIR}/${SERVICE_NAME}.plist"
    echo "  Main service loaded"
fi

if [[ -f "./update.sh" ]]; then
    rm -f "${EXEC_DIR}/update.sh.old" 2>/dev/null || true
    if [[ -f "${EXEC_DIR}/update.sh.current" ]]; then
        mv "${EXEC_DIR}/update.sh.current" "${EXEC_DIR}/update.sh.old" 2>/dev/null || true
    fi
    install -m 740 "./update.sh" "${EXEC_DIR}/update.sh.current"
    ln -sf "update.sh.current" "${EXEC_DIR}/update.sh"
fi

if [[ -f "./update.conf" ]]; then
    if [[ -f "./nebula_nebula10-update.plist" ]]; then
        install -m 644 "./nebula_nebula10-update.plist" "${LAUNCH_DAEMONS_DIR}/"
        if launchctl list | grep -q "${SERVICE_NAME}-update"; then
            echo "  Update service loaded"
        else
            if sudo launchctl bootstrap system "${LAUNCH_DAEMONS_DIR}/${SERVICE_NAME}-update.plist"; then
                echo "  Update service loaded"
            else
                echo "  ERROR: Failed to load update service"
                exit 1
            fi
        fi
    fi
fi

echo -e "* If the device is a lighthouse, you may also need to adjust your firewall"
echo "  to allow traffic to the @@tun_device@@ network device port"

echo -e "Done. If there were no errors, you can remove this deployment package\n"

exit 0