# ============================================================================
# Removal script for Windows - execute as administrator in PowerShell
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================

$ErrorActionPreference = "Stop"
$InstallDir = "C:\nebula\@@tun_device@@"

function Write-Log { param([string]$Msg) Write-Host "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] $Msg" }

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run as Administrator"
}

Write-Log "Nebula Removal"
Write-Log "Target: $InstallDir"

$taskName = "Nebula-@@tun_device@@ Auto-Update"
Write-Log "Removing scheduled task: $taskName"
try {
    $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($task) {
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
        Write-Log "Scheduled task removed"
    } else {}
}
catch {}

$serviceName = "Nebula"
$service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue

if ($service) {

    if ($service.Status -eq 'Running') {
        Write-Log "Stopping service"
        $nebulaExe = Join-Path $InstallDir "nebula.exe"
        if (Test-Path $nebulaExe) {
            & $nebulaExe -service stop 2>&1 | Out-Null
        } else {
            Stop-Service -Name $serviceName -Force -ErrorAction SilentlyContinue
        }
        Start-Sleep -Seconds 3
    }

    Write-Log "Uninstalling service"
    if (Test-Path $nebulaExe) {
        & $nebulaExe -service uninstall 2>&1 | Out-Null
    } else {
        sc.exe delete $serviceName 2>&1 | Out-Null
    }
    Start-Sleep -Seconds 2

    if (Get-Service -Name $serviceName -ErrorAction SilentlyContinue) {
        sc.exe delete $serviceName 2>&1 | Out-Null
    } else {
        Write-Log "Service uninstalled"
    }
}

Set-Location -Path "C:\"

Write-Log "Deleting directory: $InstallDir"
if (Test-Path $InstallDir) {
    try {
        Remove-Item -Path $InstallDir -Recurse -Force -ErrorAction Stop
        Write-Log "Directory deleted"
    }
    catch {
        Write-Log "Could not delete directory"
    }
}

Write-Log "Removal completed"