#!/bin/bash

# ============================================================================
# Clean-up script for Linux - execute with sudo bash
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================

set -euo pipefail

EXEC_DIR="/usr/lib/nebula/@@tun_device@@"
CONFIG_DIR="/etc/nebula/@@tun_device@@"
SERVICE_DIR="/etc/systemd/system"
SERVICE_NAME="nebula_@@tun_device@@"

echo -e "\nThis is a clean-up script generated by nebulder (https://github.com/erykjj/nebulder)\nfor automating the removal of a Nebula network device under Linux with systemd\n"

if [ "$(id -u)" != "0" ]; then
 echo -e "* Because of the high-level access required to execute these commands,\n  this script needs to be run as root\n"
 exit 1
fi

echo "* Cleaning up systemd services"
systemctl stop "${SERVICE_NAME}-update.timer" 2>/dev/null || true
systemctl stop "${SERVICE_NAME}-update.service" 2>/dev/null || true
systemctl stop "${SERVICE_NAME}.service" 2>/dev/null || true
systemctl disable "${SERVICE_NAME}-update.timer" 2>/dev/null || true
systemctl disable "${SERVICE_NAME}-update.service" 2>/dev/null || true
systemctl disable "${SERVICE_NAME}.service" 2>/dev/null || true
rm -f "${SERVICE_DIR}/${SERVICE_NAME}.service" \
      "${SERVICE_DIR}/${SERVICE_NAME}-update.service" \
      "${SERVICE_DIR}/${SERVICE_NAME}-update.timer" 2>/dev/null || true
systemctl daemon-reload 2>/dev/null || true
echo -e "  Unit files removed\n"

echo "* Removing config and keys from ${CONFIG_DIR}"
if [[ -d "${CONFIG_DIR}" ]]; then
  rm -rf "${CONFIG_DIR}"
  echo "  Config directory removed"
fi

echo "* Removing scripts and binary from ${EXEC_DIR}"
if [[ -d "/var/run/nebula/@@tun_device@@" ]]; then
  rm -rf "/var/run/nebula/@@tun_device@@"
fi
if [[ -d "${EXEC_DIR}" ]]; then
  rm -rf "${EXEC_DIR}"
  echo "  Script and binary directory removed"
fi

echo -e "\n* Optional cleanup (may affect other Nebula networks):"
echo "  - Check for other configs: 'sudo ls /etc/nebula/'"
echo "  - Check for other exec dirs: 'sudo ls /usr/lib/nebula/'"
echo "  - Remove nebula user if no other networks: 'sudo userdel nebula'"
echo "  - Check firewall rules: 'sudo ufw status numbered'"

echo -e "\nDone. If there were no errors, you can remove this script/deployment package\n"

exit 0