#!/bin/bash

# ============================================================================
# Clean-up script for macOS - execute with sudo bash
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================

set -euo pipefail

EXEC_DIR="/usr/local/lib/nebula/@@tun_device@@"
CONFIG_DIR="/usr/local/etc/nebula/@@tun_device@@"
LAUNCH_DAEMONS_DIR="/Library/LaunchDaemons"
SERVICE_NAME="nebula_@@tun_device@@"

echo -e "\nmacOS removal script for Nebula network @@tun_device@@\n"

if [[ "$(id -u)" != "0" ]]; then
    echo "This script must be run as root (use sudo)."
    exit 1
fi

echo "* Stopping and removing launchd services"
sudo launchctl bootout system "${LAUNCH_DAEMONS_DIR}/${SERVICE_NAME}.plist" 2>/dev/null || true
sudo launchctl bootout system "${LAUNCH_DAEMONS_DIR}/${SERVICE_NAME}-update.plist" 2>/dev/null || true
rm -f "${LAUNCH_DAEMONS_DIR}/${SERVICE_NAME}.plist" \
      "${LAUNCH_DAEMONS_DIR}/${SERVICE_NAME}-update.plist" 2>/dev/null || true
echo "  Services unloaded and plist files removed."

echo -e "\n* Removing config and keys from ${CONFIG_DIR}"
if [[ -d "${CONFIG_DIR}" ]]; then
    rm -rf "${CONFIG_DIR}"
    echo "  Config directory removed."
fi

echo -e "\n* Removing scripts and binary from ${EXEC_DIR}"
if [[ -d "/var/run/nebula/@@tun_device@@" ]]; then
    rm -rf "/var/run/nebula/@@tun_device@@"
fi
if [[ -d "${EXEC_DIR}" ]]; then
    rm -rf "${EXEC_DIR}"
    echo "  Script and binary directory removed."
fi

echo -e "\n* Optional cleanup (may affect other Nebula networks):"
echo "  - Check for other configs: sudo ls /usr/local/etc/nebula/"
echo "  - Check for other exec dirs: sudo ls /usr/local/lib/nebula/"
echo "  - Check launchd plists: sudo ls ${LAUNCH_DAEMONS_DIR}/nebula_*"

echo -e "\nDone."
exit 0