#!/bin/bash

# ============================================================================
# Self-update script for macOS - execute with sudo bash
# Generated by nebulder - https://github.com/erykjj/nebulder
# MIT License: Copyright (c) 2026 Eryk J.
# ============================================================================

set -euo pipefail

# ----------------------------------------------------------------------------
# Configuration and Paths (macOS-specific)
# ----------------------------------------------------------------------------
EXEC_DIR="/usr/local/lib/nebula/@@tun_device@@"
NEBULA_BINARY="${EXEC_DIR}/nebula"
UPDATE_SCRIPT="${EXEC_DIR}/update.sh"
CONFIG_DIR="/usr/local/etc/nebula/@@tun_device@@"
CONFIG_FILE="${CONFIG_DIR}/update.conf"
LOCAL_VERSION_FILE="${CONFIG_DIR}/version"
LOCAL_NODE_FILE="${LOCAL_NODE_FILE:-${CONFIG_DIR}/node}"
BACKUP_DIR="/var/backups/@@tun_device@@"
SERVICE_NAME="nebula_@@tun_device@@"
CONNECTIVITY_PROBE="https://api.github.com"

# ----------------------------------------------------------------------------
# Global State
# ----------------------------------------------------------------------------
FAILURE_REASON=""
NODE_NAME=""
OLD_VERSION=""
REMOTE_VERSION=""
TEMP_DIR=""
BACKUP_CREATED=false
SOURCE_USED=""
UPDATE_PRIMARY=""
UPDATE_SECONDARY=""

# ----------------------------------------------------------------------------
# Core Functions (Critical - exit on failure)
# ----------------------------------------------------------------------------

load_configuration() {
    if [[ ! -f "${CONFIG_FILE}" ]]; then
        echo "ERROR: Configuration file not found: ${CONFIG_FILE}" >&2
        exit 1
    fi
    source "${CONFIG_FILE}"

    local server="${UPDATE_SERVER:-}"
    local github="${GITHUB_REPO:-}"

    if [[ -z "${server}" && -z "${github}" ]]; then
        echo "ERROR: Neither UPDATE_SERVER nor GITHUB_REPO configured in ${CONFIG_FILE}" >&2
        exit 1
    fi

    if [[ -n "${server}" ]]; then
        if [[ -z "${AUTH_USER:-}" || -z "${AUTH_PASS:-}" ]]; then
            echo "ERROR: AUTH_USER and AUTH_PASS required when UPDATE_SERVER is set" >&2
            exit 1
        fi
    fi

    if [[ -n "${github}" ]]; then
        if [[ -z "${UPDATE_TOKEN:-}" ]]; then
            echo "ERROR: UPDATE_TOKEN required when GITHUB_REPO is set" >&2
            exit 1
        fi
    fi

    if [[ -z "${UPDATE_PASS:-}" ]]; then
        echo "ERROR: UPDATE_PASS missing in ${CONFIG_FILE}" >&2
        exit 1
    fi

    if [[ -n "${server}" && -n "${github}" ]]; then
        if [[ "${UPDATE_PRIMARY:-}" != "server" && "${UPDATE_PRIMARY:-}" != "github" ]]; then
            echo "ERROR: UPDATE_PRIMARY must be 'server' or 'github' when both sources are set" >&2
            exit 1
        fi
        if [[ "${UPDATE_PRIMARY}" == "server" ]]; then
            UPDATE_SECONDARY="github"
        else
            UPDATE_SECONDARY="server"
        fi
    elif [[ -n "${server}" ]]; then
        UPDATE_PRIMARY="server"
        UPDATE_SECONDARY=""
    else
        UPDATE_PRIMARY="github"
        UPDATE_SECONDARY=""
    fi

    NTFY_CHANNEL="${NTFY_CHANNEL:-}"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "ERROR: This script must be run as root" >&2
        exit 2
    fi
}

check_dependencies() {
    local required_commands=("curl" "unzip" "openssl" "awk" "grep" "sed")
    for cmd in "${required_commands[@]}"; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            echo "ERROR: Missing required dependency: $cmd" >&2
            exit 1
        fi
    done
}

# ----------------------------------------------------------------------------
# Helper Functions (Non-critical - set FAILURE_REASON on error)
# ----------------------------------------------------------------------------

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

get_local_version() {
    if [[ -f "${LOCAL_VERSION_FILE}" ]]; then
        cat "${LOCAL_VERSION_FILE}" 2>/dev/null | tr -d '[:space:]' || echo "0.0.0"
    else
        echo "0.0.0"
    fi
}

get_node_name() {
    if [[ ! -f "${LOCAL_NODE_FILE}" ]]; then
        return 1
    fi
    local node_content=$(cat "${LOCAL_NODE_FILE}" 2>/dev/null | tr -d '[:space:]')
    if [[ -z "$node_content" ]]; then
        return 1
    fi
    echo "$node_content"
    return 0
}

get_nebula_version() {
    if [[ -f "$NEBULA_BINARY" ]]; then
        "$NEBULA_BINARY" --version 2>/dev/null | grep -o "Version: [0-9.]*" | cut -d' ' -f2 || echo "unknown"
    else
        echo "not_found"
    fi
}

trim_log() {
    local log_file="$1"
    local max_size_mb=1
    local max_size_bytes=$((max_size_mb * 1024 * 1024))
    if [[ -f "$log_file" ]] && [[ $(stat -f%z "$log_file" 2>/dev/null || echo 0) -gt $max_size_bytes ]]; then
        tail -c ${max_size_bytes} "$log_file" > "${log_file}.tmp" && mv "${log_file}.tmp" "$log_file"
    fi
}

check_connectivity() {
    local route_attempts=5
    local route_wait=10
    for ((i=1; i<=route_attempts; i++)); do
        if netstat -rn | grep -q '^default'; then
            break
        fi
        log "Waiting for default route ($i/$route_attempts)"
        sleep $route_wait
    done

    if ! netstat -rn | grep -q '^default'; then
        FAILURE_REASON="NETWORK_UNREACHABLE"
        log "No default route available"
        return 1
    fi

    local probe_attempts=5
    local attempt=1
    while [[ $attempt -le $probe_attempts ]]; do
        if curl -s -I --connect-timeout 5 --max-time 10 "${CONNECTIVITY_PROBE}/" >/dev/null 2>&1; then
            return 0
        fi
        log "Internet connectivity check failed (attempt $attempt/$probe_attempts)"
        sleep 20
        ((attempt++))
    done

    FAILURE_REASON="NETWORK_UNREACHABLE"
    return 1
}

# ----------------------------------------------------------------------------
# Source: Server
# ----------------------------------------------------------------------------

server_check_remote_version() {
    local curl_output
    local http_code
    local max_retries=2
    local retry_count=0

    while [[ $retry_count -le $max_retries ]]; do
        curl_output=$(curl -s -w "%{http_code}" -u "${AUTH_USER}:${AUTH_PASS}" \
            --connect-timeout 10 \
            --max-time 15 \
            "${UPDATE_SERVER}/version.txt" 2>/dev/null)

        http_code=${curl_output: -3}
        curl_output=${curl_output%???}

        if [[ "$http_code" =~ ^[0-9]{3}$ ]] && [[ "$http_code" != "000" ]]; then
            break
        fi

        if [[ $retry_count -lt $max_retries ]]; then
            log "Retrying connection to update server..."
            sleep 3
        fi
        ((retry_count++))
    done

    if [[ ! "$http_code" =~ ^[0-9]{3}$ ]] || [[ "$http_code" == "000" ]]; then
        FAILURE_REASON="SERVER_UNREACHABLE"
        log "Update server unreachable after $max_retries retries"
        return 1
    fi

    if [[ "$http_code" != "200" ]]; then
        if [[ "$http_code" == "401" ]] || [[ "$http_code" == "403" ]]; then
            FAILURE_REASON="AUTH_FAILED"
            log "Authentication failed"
            return 1
        else
            REMOTE_VERSION=""
            return 0
        fi
    fi

    REMOTE_VERSION=$(echo "$curl_output" | tr -d '[:space:]')
    if [[ -z "${REMOTE_VERSION}" ]]; then
        REMOTE_VERSION=""
    fi
    return 0
}

server_download_package() {
    local remote_version="$1"
    local package_name="${NODE_NAME}_${remote_version}.zip.enc"
    local package_url="${UPDATE_SERVER}/${package_name}"

    TEMP_DIR=$(mktemp -d -t nebula-update-XXXXXX)

    log "Downloading encrypted package (server)"
    if ! curl -s -u "${AUTH_USER}:${AUTH_PASS}" --connect-timeout 30 -o "${TEMP_DIR}/package.enc" "${package_url}"; then
        FAILURE_REASON="DOWNLOAD_FAILED"
        log "Package download failed"
        return 1
    fi

    if [[ ! -s "${TEMP_DIR}/package.enc" ]]; then
        FAILURE_REASON="DOWNLOAD_FAILED"
        log "Package download produced empty file"
        return 1
    fi

    if ! step_decrypt_package "${TEMP_DIR}/package.enc" "${TEMP_DIR}/package.zip"; then
        FAILURE_REASON="DECRYPTION_FAILED"
        log "Package decryption failed"
        return 1
    fi
    rm -f "${TEMP_DIR}/package.enc"

    if ! unzip -q -d "${TEMP_DIR}" "${TEMP_DIR}/package.zip" 2>/dev/null; then
        FAILURE_REASON="INVALID_PACKAGE"
        log "Invalid or missing package"
        return 1
    fi
    rm -f "${TEMP_DIR}/package.zip"

    return 0
}

# ----------------------------------------------------------------------------
# Source: GitHub
# ----------------------------------------------------------------------------

github_fetch_release() {
    local response
    local http_code
    local max_retries=2
    local retry_count=0

    GITHUB_RELEASE_JSON=""
    GITHUB_TAG_NAME=""

    while [[ $retry_count -le $max_retries ]]; do
        response=$(curl -s -w "\n%{http_code}" \
            -H "Authorization: Bearer ${UPDATE_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            --connect-timeout 10 \
            --max-time 15 \
            "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" 2>/dev/null)

        http_code=$(echo "$response" | tail -n1)
        response=$(echo "$response" | sed '$d')

        if [[ "$http_code" =~ ^[0-9]{3}$ ]] && [[ "$http_code" != "000" ]]; then
            break
        fi

        if [[ $retry_count -lt $max_retries ]]; then
            log "Retrying connection to GitHub..."
            sleep 3
        fi
        ((retry_count++))
    done

    if [[ ! "$http_code" =~ ^[0-9]{3}$ ]] || [[ "$http_code" == "000" ]]; then
        FAILURE_REASON="SERVER_UNREACHABLE"
        log "GitHub unreachable after $max_retries retries"
        return 1
    fi

    if [[ "$http_code" != "200" ]]; then
        if [[ "$http_code" == "401" ]] || [[ "$http_code" == "403" ]] || [[ "$http_code" == "404" ]]; then
            FAILURE_REASON="AUTH_FAILED"
            log "GitHub authentication failed (HTTP $http_code)"
            return 1
        else
            FAILURE_REASON="SERVER_UNREACHABLE"
            log "GitHub returned HTTP $http_code"
            return 1
        fi
    fi

    GITHUB_RELEASE_JSON="$response"
    GITHUB_TAG_NAME=$(printf '%s\n' "$GITHUB_RELEASE_JSON" \
        | grep -m1 '"tag_name"' \
        | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')

    if [[ -z "$GITHUB_TAG_NAME" ]]; then
        FAILURE_REASON="SERVER_UNREACHABLE"
        log "Could not parse tag_name from GitHub response"
        return 1
    fi

    REMOTE_VERSION="$GITHUB_TAG_NAME"
    return 0
}

github_download_package() {
    local remote_version="$1"
    local asset_name="${NODE_NAME}_${remote_version}.zip.enc"

    TEMP_DIR=$(mktemp -d -t nebula-update-XXXXXX)

    local blocks
    blocks=$(printf '%s\n' "$GITHUB_RELEASE_JSON" | awk '
        /^    \{/    { block=$0; in_asset=1; next }
        in_asset     { block = block $0 }
        /^    \},?$/ { if (in_asset) { print block; in_asset=0 } }
    ')

    local block
    block=$(printf '%s\n' "$blocks" | grep "\"name\": \"$asset_name\"" || true)

    if [[ -z "$block" ]]; then
        FAILURE_REASON="ASSET_NOT_FOUND"
        log "Asset '$asset_name' not found in GitHub release $remote_version"
        return 1
    fi

    local asset_url
    asset_url=$(printf '%s\n' "$block" | grep -o 'https://api.github.com[^"]*/releases/assets/[0-9]*')

    if [[ -z "$asset_url" ]]; then
        FAILURE_REASON="ASSET_NOT_FOUND"
        log "Could not extract asset URL for '$asset_name'"
        return 1
    fi

    log "Downloading encrypted package (github)"
    if ! curl -L -s -H "Authorization: Bearer ${UPDATE_TOKEN}" \
         -H "Accept: application/octet-stream" \
         --connect-timeout 30 \
         -o "${TEMP_DIR}/package.enc" \
         "$asset_url"; then
        FAILURE_REASON="DOWNLOAD_FAILED"
        log "Package download failed"
        return 1
    fi

    if [[ ! -s "${TEMP_DIR}/package.enc" ]]; then
        FAILURE_REASON="DOWNLOAD_FAILED"
        log "Package download produced empty file"
        return 1
    fi

    if ! step_decrypt_package "${TEMP_DIR}/package.enc" "${TEMP_DIR}/package.zip"; then
        FAILURE_REASON="DECRYPTION_FAILED"
        log "Package decryption failed"
        return 1
    fi
    rm -f "${TEMP_DIR}/package.enc"

    if ! unzip -q -d "${TEMP_DIR}" "${TEMP_DIR}/package.zip" 2>/dev/null; then
        FAILURE_REASON="INVALID_PACKAGE"
        log "Invalid or missing package"
        return 1
    fi
    rm -f "${TEMP_DIR}/package.zip"

    return 0
}

# ----------------------------------------------------------------------------
# Shared Package Handling
# ----------------------------------------------------------------------------

step_decrypt_package() {
    local encrypted_file="$1"
    local output_file="$2"
    if [[ ! -f "$encrypted_file" ]] || [[ ! -r "$encrypted_file" ]]; then
        log "ERROR: Encrypted file not found or not readable"
        return 1
    fi
    local file_size=$(stat -f%z "$encrypted_file" 2>/dev/null)
    if [[ $file_size -lt 16 ]]; then
        log "ERROR: Encrypted file too small"
        return 1
    fi
    if openssl enc -aes-256-cbc -d -salt -pbkdf2 -iter 100000 \
        -in "$encrypted_file" \
        -out "$output_file" \
        -pass "pass:${UPDATE_PASS}" 2>/dev/null; then
        log "Package decrypted successfully"
        return 0
    else
        log "ERROR: openssl decryption failed"
        return 1
    fi
}

# ----------------------------------------------------------------------------
# Update Steps
# ----------------------------------------------------------------------------

step_validate_node() {
    local node_name
    if ! node_name=$(get_node_name); then
        FAILURE_REASON="NODE_NAME_MISSING"
        log "Node name file missing or empty"
        local config_yaml="${CONFIG_DIR}/config.yaml"
        if [[ -f "$config_yaml" ]]; then
            local first_line=$(head -n 1 "$config_yaml" 2>/dev/null || echo "")
            if [[ "$first_line" == \#* ]]; then
                FAILURE_REASON="${FAILURE_REASON} (${first_line})"
            fi
        fi
        return 1
    fi
    NODE_NAME="$node_name"
    return 0
}

step_create_backup() {
    rm -rf "${BACKUP_DIR}"
    mkdir -p "${BACKUP_DIR}/config"
    mkdir -p "${BACKUP_DIR}/launchd"
    mkdir -p "${BACKUP_DIR}/exec"

    for plist in "${SERVICE_NAME}.plist" "${SERVICE_NAME}-update.plist"; do
        if [[ -f "/Library/LaunchDaemons/${plist}" ]]; then
            cp -a "/Library/LaunchDaemons/${plist}" "${BACKUP_DIR}/launchd/" 2>/dev/null || true
        fi
    done

    if [[ -d "${EXEC_DIR}" ]]; then
        cp -a "${EXEC_DIR}"/*.sh "${BACKUP_DIR}/exec/" 2>/dev/null || true
    fi

    if [[ -f "${NEBULA_BINARY}" ]]; then
        cp -a "${NEBULA_BINARY}" "${BACKUP_DIR}/exec/" 2>/dev/null || true
    fi

    if [[ -d "${CONFIG_DIR}" ]]; then
        cp -a "${CONFIG_DIR}/"* "${BACKUP_DIR}/config/" 2>/dev/null || true
    fi

    BACKUP_CREATED=true
    log "Backup created"
    return 0
}

step_apply_update() {
    local temp_dir="$1"

    cd "${temp_dir}" || {
        FAILURE_REASON="CANNOT_CD_TEMP"
        log "Cannot access temp directory"
        return 1
    }

    if [[ ! -f "./deploy.sh" ]]; then
        FAILURE_REASON="NO_DEPLOY_SCRIPT"
        log "Missing deploy.sh in package"
        return 1
    fi

    chmod +x ./deploy.sh
    log "Running deploy.sh..."

    if ! ./deploy.sh; then
        FAILURE_REASON="DEPLOY_FAILED"
        log "deploy.sh failed"
        return 1
    fi

    log "Update applied"
    return 0
}

step_verify_update() {
    local expected_version="$1"
    local new_local_version

    sync
    sleep 1

    new_local_version=$(get_local_version)

    if [[ "$new_local_version" != "$expected_version" ]]; then
        FAILURE_REASON="VERIFICATION_FAILED"
        log "Version mismatch after update"
        return 1
    fi

    log "Update verified"
    return 0
}

step_restore_backup() {
    if [[ "$BACKUP_CREATED" != true ]]; then
        return 0
    fi

    log "Restoring from backup"

    if [[ ! -d "${BACKUP_DIR}" ]]; then
        log "Backup directory not found"
        return 1
    fi

    sudo launchctl bootout system "/Library/LaunchDaemons/${SERVICE_NAME}.plist" 2>/dev/null || true
    sleep 2

    if [[ -d "${BACKUP_DIR}/exec" ]]; then
        cp -a "${BACKUP_DIR}/exec"/*.sh "${EXEC_DIR}/" 2>/dev/null || true
    fi

    if [[ -f "${BACKUP_DIR}/exec/nebula" ]]; then
        cp -a "${BACKUP_DIR}/exec/nebula" "${NEBULA_BINARY}"
    fi

    if [[ -d "${BACKUP_DIR}/config" ]]; then
        rm -rf "${CONFIG_DIR}"
        mkdir -p "${CONFIG_DIR}"
        cp -a "${BACKUP_DIR}/config/"* "${CONFIG_DIR}/" 2>/dev/null || true
    fi

    if [[ -d "${BACKUP_DIR}/launchd" ]]; then
        for plist in "${BACKUP_DIR}/launchd"/*.plist; do
            if [[ -f "$plist" ]]; then
                cp -a "$plist" "/Library/LaunchDaemons/"
            fi
        done
    fi

    log "Reloading service..."
    sudo launchctl bootstrap system "/Library/LaunchDaemons/${SERVICE_NAME}.plist" 2>/dev/null || true

    log "Backup restored"
    return 0
}

step_check_service() {
    if launchctl print "system/${SERVICE_NAME}" >/dev/null 2>&1; then
        log "Service loaded"
        return 0
    else
        FAILURE_REASON="SERVICE_NOT_LOADED"
        log "Service not loaded in launchd"
        return 1
    fi
}

step_trim_logs() {
    trim_log "/usr/local/var/log/nebula_@@tun_device@@.log"
    trim_log "/usr/local/var/log/nebula_@@tun_device@@-update.log"
    log "Logs trimmed"
    return 0
}

# ----------------------------------------------------------------------------
# Cleanup and Reporting
# ----------------------------------------------------------------------------

cleanup_temp() {
    if [[ -n "$TEMP_DIR" ]] && [[ -d "$TEMP_DIR" ]]; then
        rm -rf "$TEMP_DIR"
    fi
}

cleanup_backup() {
    if [[ -d "$BACKUP_DIR" ]]; then
        rm -rf "$BACKUP_DIR"
    fi
}

notify_ntfy() {
    local priority="$1"
    local tags="$2"
    local message="$3"

    if [[ -z "${NTFY_CHANNEL:-}" ]]; then
        return 0
    fi

    local channel_clean=$(echo "${NTFY_CHANNEL}" | tr -d '[:space:]')
    if [[ -z "$channel_clean" ]]; then
        return 0
    fi

    local ntfy_url="https://ntfy.sh/${channel_clean}"
    echo "$message" | \
        curl -H "Title: ${NODE_NAME} @ @@tun_device@@" \
             -H "Tags:${tags}" \
             -H "Priority:${priority}" \
             --data-binary @- "${ntfy_url}" >/dev/null 2>&1 || true
}

report_result() {
    local result_code="$1"
    local nebula_version=$(get_nebula_version)
    local result_text=""

    case $result_code in
        0) result_text="success" ;;
        1) result_text="no_update" ;;
        2) result_text="error" ;;
        3) result_text="interrupted" ;;
        4) result_text="offline" ;;
    esac

    local status_dir="/var/run/nebula/@@tun_device@@"
    mkdir -p "$status_dir"
    cat > "${status_dir}/update-status.json" << EOF
{
"node": "$NODE_NAME",
"result": "$result_text",
"previous": "$OLD_VERSION",
"current": "$REMOTE_VERSION",
"nebula": "$nebula_version",
"source": "$SOURCE_USED",
"failure_reason": "$FAILURE_REASON",
"timestamp": "$(date -Iseconds)"
}
EOF
    chmod 755 "$status_dir" 2>/dev/null || true
    chmod 644 "${status_dir}/update-status.json" 2>/dev/null || true

    case $result_code in
        0)
            notify_ntfy "3" "white_check_mark" \
                "Updated: ${OLD_VERSION} → ${REMOTE_VERSION}"$'\n'"Source: ${SOURCE_USED}"$'\n'"Nebula: ${nebula_version}"
            ;;
        2)
            local msg
            if [[ -n "$REMOTE_VERSION" ]]; then
                msg="Update to ${REMOTE_VERSION} FAILED"
            else
                msg="Update FAILED"
            fi
            msg="${msg}"$'\n'"Node: ${NODE_NAME}"$'\n'"Reason: ${FAILURE_REASON}"
            if [[ -n "$SOURCE_USED" ]]; then
                msg="${msg}"$'\n'"Source: ${SOURCE_USED}"
            fi
            msg="${msg}"$'\n'"Nebula: ${nebula_version}"
            notify_ntfy "4" "warning" "$msg"
            ;;
    esac
}

# ----------------------------------------------------------------------------
# Main Control Flow
# ----------------------------------------------------------------------------

handle_interruption() {
    log "Update interrupted"
    FAILURE_REASON="INTERRUPTED"
    if [[ "$BACKUP_CREATED" == true ]]; then
        step_restore_backup
    fi
    cleanup_temp
    cleanup_backup
    report_result 3
    exit 3
}

try_source_version() {
    local source="$1"
    FAILURE_REASON=""
    REMOTE_VERSION=""
    if [[ "$source" == "server" ]]; then
        server_check_remote_version
    else
        github_fetch_release
    fi
}

try_source_download() {
    local source="$1"
    local version="$2"
    if [[ "$source" == "server" ]]; then
        server_download_package "$version"
    else
        github_download_package "$version"
    fi
}

main() {
    trap 'handle_interruption' INT TERM

    # Critical initialization (exit on failure)
    check_root
    load_configuration
    check_dependencies

    # Get node name early for reporting
    NODE_NAME=$(get_node_name || echo "UNKNOWN")

    if ! check_connectivity; then
        log "Node offline - will retry next cycle"
        report_result 4
        exit 0
    fi

    OLD_VERSION=$(get_local_version)

    # ------------------------------------------------------------------------
    # Try primary source, fall back to secondary on transport/auth failure
    # ------------------------------------------------------------------------
    local primary="$UPDATE_PRIMARY"
    local secondary="$UPDATE_SECONDARY"

    SOURCE_USED="$primary"
    if ! try_source_version "$primary"; then
        if [[ -n "$secondary" ]]; then
            log "Primary source ($primary) failed: $FAILURE_REASON - trying $secondary"
            notify_ntfy "2" "warning" \
                "Primary source ($primary) failed: $FAILURE_REASON"$'\n'"Trying $secondary"
            FAILURE_REASON=""
            SOURCE_USED="$secondary"
            if ! try_source_version "$secondary"; then
                report_result 2
                log "Update failed: $FAILURE_REASON"
                exit 2
            fi
        else
            report_result 2
            log "Update failed: $FAILURE_REASON"
            exit 2
        fi
    fi

    # ------------------------------------------------------------------------
    # Evaluate version
    # ------------------------------------------------------------------------
    if [[ -z "$REMOTE_VERSION" ]]; then
        log "No update available (no version on $SOURCE_USED)"
        report_result 1
        exit 1
    fi

    if [[ "$OLD_VERSION" == "$REMOTE_VERSION" ]]; then
        log "Already at version $OLD_VERSION"
        report_result 1
        exit 1
    fi

    log "Updating: $OLD_VERSION → $REMOTE_VERSION (via $SOURCE_USED)"

    # ------------------------------------------------------------------------
    # Validate node name
    # ------------------------------------------------------------------------
    if ! step_validate_node; then
        report_result 2
        log "Update failed: $FAILURE_REASON"
        exit 2
    fi

    # ------------------------------------------------------------------------
    # Download (no fallback on ASSET_NOT_FOUND)
    # ------------------------------------------------------------------------
    if ! try_source_download "$SOURCE_USED" "$REMOTE_VERSION"; then
        if [[ "$FAILURE_REASON" == "ASSET_NOT_FOUND" ]]; then
            log "Asset not found in release - not falling back"
        fi
        report_result 2
        log "Update failed: $FAILURE_REASON"
        exit 2
    fi

    # ------------------------------------------------------------------------
    # Backup
    # ------------------------------------------------------------------------
    if ! step_create_backup; then
        cleanup_temp
        report_result 2
        log "Update failed: BACKUP_FAILED"
        exit 2
    fi

    # ------------------------------------------------------------------------
    # Apply
    # ------------------------------------------------------------------------
    if ! step_apply_update "$TEMP_DIR"; then
        step_restore_backup
        cleanup_temp
        cleanup_backup
        report_result 2
        log "Update failed: $FAILURE_REASON"
        exit 2
    fi

    # ------------------------------------------------------------------------
    # Verify
    # ------------------------------------------------------------------------
    if ! step_verify_update "$REMOTE_VERSION"; then
        step_restore_backup
        cleanup_temp
        cleanup_backup
        report_result 2
        log "Update failed: $FAILURE_REASON"
        exit 2
    fi

    # ------------------------------------------------------------------------
    # Check service (warning only)
    # ------------------------------------------------------------------------
    step_check_service || true

    # ------------------------------------------------------------------------
    # Trim logs
    # ------------------------------------------------------------------------
    step_trim_logs

    # Success
    cleanup_temp
    cleanup_backup
    log "Update completed"
    report_result 0
    exit 0
}

main "$@"