@echo off
REM ============================================================================
REM Wrapper for update.ps1
REM Generated by nebulder - https://github.com/erykjj/nebulder
REM MIT License: Copyright (c) 2026 Eryk J.
REM ============================================================================

setlocal

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

cd /d "%SCRIPT_DIR%" 2>nul
if errorlevel 1 (
    echo ERROR: Cannot change to directory: %SCRIPT_DIR%
    exit /b 2
)

if not exist "update.ps1" (
    echo ERROR: update.ps1 not found
    exit /b 2
)

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "update.ps1"

set "EXIT_CODE=%errorlevel%"

endlocal
exit /b %EXIT_CODE%